# -*- coding: utf-8 -*-
"""RuleBasedExpertSystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aoqArkGDDa0rWQ2iYYhll-Hp_34xrzzI

# 🧠 Rule-Based Expert System
### Forward Chaining Inference Engine — Medical Diagnosis Domain

---

**Project features:**
- ✅ IF-THEN rule engine with priority-based firing  
- ✅ Multi-step forward chaining (conclusions feed new inferences)  
- ✅ Full inference trace / reasoning path log  
- ✅ Interactive symptom selector using `ipywidgets`  
- ✅ 17 rules · 25 symptoms · 7 demo scenarios

> ⚕️ *Disclaimer: For educational purposes only. Not for real medical use.*

## 📦 1. Install Dependencies
"""

# Run this cell once if ipywidgets is not installed
import subprocess, sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "ipywidgets", "--break-system-packages", "-q"])
print("✓ Dependencies ready")

"""---
## ⚙️ 2. Inference Engine

The core forward-chaining engine.  
**Algorithm:** Scan all rules → fire the highest-priority unfired rule whose conditions are all True → add its conclusion to the fact base → repeat until fixpoint.

"""

from dataclasses import dataclass, field
from typing import Any
import copy

@dataclass
class Rule:
    """Represents a single IF-THEN rule."""
    rule_id:          str
    name:             str
    conditions:       list   # fact keys that must be True
    conclusion:       str    # fact key added when rule fires
    conclusion_value: Any  = True
    explanation:      str  = ""
    priority:         int  = 0

    def __repr__(self):
        cond_str = " AND ".join(self.conditions)
        return f"Rule({self.rule_id}): IF {cond_str} THEN {self.conclusion}"


@dataclass
class InferenceStep:
    """Records one fired rule in the reasoning chain."""
    step_number:       int
    rule:              Rule
    triggered_by:      list
    conclusion_added:  str
    conclusion_value:  Any
    facts_before:      dict
    facts_after:       dict


class ForwardChainer:
    """
    Forward-chaining inference engine.

    1. Load initial facts.
    2. Find the highest-priority unfired rule whose conditions are all satisfied.
    3. Fire it → add conclusion to facts → log the step.
    4. Repeat until no rule can fire (fixpoint).
    """

    def __init__(self, rules: list):
        self.rules = sorted(rules, key=lambda r: -r.priority)
        self.reset()

    def reset(self):
        self.facts:         dict = {}
        self.inference_log: list = []
        self.fired_rules:   set  = set()

    def load_facts(self, facts: dict):
        self.facts.update(facts)

    def _conditions_met(self, rule: Rule) -> bool:
        return all(self.facts.get(c) for c in rule.conditions)

    def run(self) -> dict:
        step, changed = 0, True
        while changed:
            changed = False
            for rule in self.rules:
                if rule.rule_id in self.fired_rules:
                    continue
                if not self._conditions_met(rule):
                    continue
                step += 1
                before = copy.deepcopy(self.facts)
                self.facts[rule.conclusion] = rule.conclusion_value
                self.fired_rules.add(rule.rule_id)
                self.inference_log.append(InferenceStep(
                    step_number=step, rule=rule,
                    triggered_by=rule.conditions,
                    conclusion_added=rule.conclusion,
                    conclusion_value=rule.conclusion_value,
                    facts_before=before,
                    facts_after=copy.deepcopy(self.facts),
                ))
                changed = True
                break  # restart with updated facts
        return self.facts

    def get_conclusions(self, exclude: set) -> dict:
        return {k: v for k, v in self.facts.items() if k not in exclude}

print("✓ Inference engine loaded  (Rule, InferenceStep, ForwardChainer)")

"""---
## 📚 3. Knowledge Base

17 IF-THEN rules across 7 medical domains, plus a catalog of 25 symptoms and 7 demo scenarios.

"""

# ── Rules ────────────────────────────────────────────────────
MEDICAL_RULES = [

    # Common Cold / Flu
    Rule("R01", "Common Cold",
         ["runny_nose","sore_throat","sneezing"], "common_cold",
         explanation="Runny nose + sore throat + sneezing → common cold.", priority=5),

    Rule("R02", "Influenza (Flu)",
         ["fever","body_aches","fatigue","cough"], "influenza",
         explanation="Fever + body aches + fatigue + cough → influenza.", priority=5),

    Rule("R03", "Severe Flu Risk",
         ["influenza","high_fever"], "severe_flu_risk",
         explanation="Flu + high fever raises risk of serious complications.", priority=6),

    # Respiratory
    Rule("R04", "Possible Pneumonia",
         ["fever","cough","chest_pain","difficulty_breathing"], "possible_pneumonia",
         explanation="Fever + cough + chest pain + breathing difficulty → pneumonia screen.", priority=7),

    Rule("R05", "Respiratory Infection",
         ["cough","fever"], "respiratory_infection",
         explanation="Cough + fever → respiratory infection.", priority=3),

    Rule("R06", "Urgent Care Needed",
         ["possible_pneumonia","high_fever"], "urgent_care_required",
         explanation="Possible pneumonia + high fever → urgent medical evaluation.", priority=9),

    # Allergy
    Rule("R07", "Seasonal Allergy",
         ["runny_nose","sneezing","itchy_eyes"], "seasonal_allergy",
         explanation="Runny nose + sneezing + itchy eyes → seasonal allergies.", priority=4),

    Rule("R08", "Allergic Reaction",
         ["itchy_skin","rash","sneezing"], "allergic_reaction",
         explanation="Itchy skin + rash + sneezing → allergic reaction.", priority=4),

    # Gastro / Dehydration
    Rule("R09", "Dehydration",
         ["vomiting","diarrhea","dizziness"], "dehydration",
         explanation="Vomiting + diarrhea + dizziness → dehydration risk.", priority=5),

    Rule("R10", "Gastroenteritis",
         ["vomiting","diarrhea","stomach_pain"], "gastroenteritis",
         explanation="Vomiting + diarrhea + stomach pain → stomach flu.", priority=5),

    Rule("R11", "IV Fluids Recommended",
         ["dehydration","gastroenteritis"], "iv_fluids_recommended",
         explanation="Dehydration + gastroenteritis → IV fluids may be required.", priority=8),

    # Cardiac / Emergency
    Rule("R12", "Cardiac Concern",
         ["chest_pain","shortness_of_breath","dizziness"], "cardiac_concern",
         explanation="Chest pain + shortness of breath + dizziness → possible cardiac event.", priority=8),

    Rule("R13", "Emergency: Possible Heart Attack",
         ["cardiac_concern","left_arm_pain"], "emergency_heart_attack",
         explanation="Cardiac concern + left arm pain → call emergency services NOW.", priority=10),

    # Neurological
    Rule("R14", "Migraine",
         ["severe_headache","nausea","light_sensitivity"], "migraine",
         explanation="Severe headache + nausea + light sensitivity → migraine.", priority=5),

    Rule("R15", "Neurological Evaluation Needed",
         ["migraine","vision_changes"], "neurological_evaluation",
         explanation="Migraine + vision changes → neurological evaluation.", priority=7),

    # Diabetes
    Rule("R16", "Possible Diabetes",
         ["frequent_urination","excessive_thirst","fatigue"], "possible_diabetes",
         explanation="Frequent urination + excessive thirst + fatigue → diabetes screening.", priority=5),

    Rule("R17", "Blood Glucose Test Required",
         ["possible_diabetes","blurred_vision"], "blood_glucose_test_required",
         explanation="Possible diabetes + blurred vision → blood glucose test.", priority=7),
]

# ── Symptom catalog ───────────────────────────────────────────
ALL_SYMPTOMS = {
    "fever":                "Fever (above 38°C / 100.4°F)",
    "high_fever":           "High fever (above 39.5°C / 103°F)",
    "cough":                "Cough",
    "sore_throat":          "Sore throat",
    "runny_nose":           "Runny nose",
    "sneezing":             "Sneezing",
    "body_aches":           "Body aches / muscle pain",
    "fatigue":              "Fatigue / tiredness",
    "difficulty_breathing": "Difficulty breathing",
    "shortness_of_breath":  "Shortness of breath",
    "chest_pain":           "Chest pain",
    "left_arm_pain":        "Left arm pain",
    "dizziness":            "Dizziness / lightheadedness",
    "nausea":               "Nausea",
    "vomiting":             "Vomiting",
    "diarrhea":             "Diarrhea",
    "stomach_pain":         "Stomach / abdominal pain",
    "itchy_eyes":           "Itchy / watery eyes",
    "itchy_skin":           "Itchy skin",
    "rash":                 "Skin rash",
    "severe_headache":      "Severe headache",
    "light_sensitivity":    "Sensitivity to light",
    "vision_changes":       "Vision changes",
    "blurred_vision":       "Blurred vision",
    "frequent_urination":   "Frequent urination",
    "excessive_thirst":     "Excessive thirst",
}

# ── Demo scenarios ─────────────────────────────────────────────
DEMO_SCENARIOS = {
    "Flu Scenario": {
        "fever","high_fever","body_aches","fatigue","cough"
    },
    "Possible Pneumonia (Urgent)": {
        "fever","high_fever","cough","chest_pain","difficulty_breathing"
    },
    "Seasonal Allergy": {
        "runny_nose","sneezing","itchy_eyes"
    },
    "Gastroenteritis + Dehydration": {
        "vomiting","diarrhea","stomach_pain","dizziness"
    },
    "Cardiac Emergency": {
        "chest_pain","shortness_of_breath","dizziness","left_arm_pain"
    },
    "Migraine + Neurological Concern": {
        "severe_headache","nausea","light_sensitivity","vision_changes"
    },
    "Possible Diabetes": {
        "frequent_urination","excessive_thirst","fatigue","blurred_vision"
    },
}

print(f"✓ Knowledge base loaded  →  {len(MEDICAL_RULES)} rules · {len(ALL_SYMPTOMS)} symptoms · {len(DEMO_SCENARIOS)} demo scenarios")

"""---
## 🖨️ 4. Display Helpers

Rich HTML rendering of the inference trace and conclusions inside the notebook.

"""

from IPython.display import display, HTML

def label(key: str) -> str:
    return ALL_SYMPTOMS.get(key, key.replace("_", " ").title())

def render_results(engine: ForwardChainer, original_keys: set):
    inferred = engine.get_conclusions(original_keys)
    log      = engine.inference_log

    # ── Classify conclusions ──────────────────────────────────
    emergency = [k for k in inferred if "emergency" in k or "urgent" in k]
    warnings  = [k for k in inferred if ("risk" in k or "required" in k or "recommended" in k) and k not in emergency]
    diagnoses = [k for k in inferred if k not in emergency and k not in warnings]

    html = []
    html.append("<style>"
        ".es-box{font-family:'Segoe UI',sans-serif;max-width:860px;margin:12px 0}"
        ".es-section{background:#1e1e2e;border-radius:10px;padding:18px 22px;margin-bottom:14px}"
        ".es-title{font-size:1.05rem;font-weight:700;letter-spacing:.04em;margin-bottom:10px}"
        ".es-chip{display:inline-block;border-radius:20px;padding:3px 12px;font-size:.82rem;margin:3px}"
        ".chip-input{background:#2a3a2a;color:#7ec87e;border:1px solid #7ec87e55}"
        ".chip-infer{background:#1a2a3a;color:#7ab8e8;border:1px solid #7ab8e855}"
        ".step-box{background:#12121f;border-left:3px solid #7ab8e8;border-radius:6px;padding:12px 16px;margin:8px 0}"
        ".step-num{color:#7ab8e8;font-weight:700;font-size:.9rem}"
        ".step-rule{color:#e2e8f0;font-weight:600}"
        ".step-cond{color:#f0c060;font-size:.85rem}"
        ".step-conc{color:#7ec87e;font-weight:600}"
        ".step-why{color:#888;font-size:.82rem;margin-top:4px}"
        ".badge-em{background:#5a1010;color:#ff6b6b;border:1px solid #ff6b6b66;border-radius:6px;padding:6px 14px;margin:4px;display:inline-block;font-weight:600}"
        ".badge-warn{background:#3a3010;color:#f0c060;border:1px solid #f0c06066;border-radius:6px;padding:6px 14px;margin:4px;display:inline-block}"
        ".badge-diag{background:#0f2a1a;color:#7ec87e;border:1px solid #7ec87e66;border-radius:6px;padding:6px 14px;margin:4px;display:inline-block}"
        ".stat-row{display:flex;gap:20px;flex-wrap:wrap;margin-top:6px}"
        ".stat-pill{background:#252535;border-radius:8px;padding:8px 16px;text-align:center}"
        ".stat-val{font-size:1.4rem;font-weight:700;color:#7ab8e8}"
        ".stat-lbl{font-size:.75rem;color:#888}"
        "</style>")

    html.append('<div class="es-box">')

    # ── Fact base ─────────────────────────────────────────────
    html.append('<div class="es-section">')
    html.append('<div class="es-title" style="color:#f0c060">📋 Input Facts (Symptoms)</div>')
    for k in original_keys:
        html.append(f'<span class="es-chip chip-input">✓ {label(k)}</span>')
    if inferred:
        html.append('<div class="es-title" style="color:#7ab8e8;margin-top:14px">🔬 Inferred Facts</div>')
        for k in inferred:
            html.append(f'<span class="es-chip chip-infer">→ {k.replace("_"," ").title()}</span>')
    html.append('</div>')

    # ── Inference trace ───────────────────────────────────────
    html.append('<div class="es-section">')
    html.append('<div class="es-title" style="color:#7ab8e8">🔗 Inference Trace — Reasoning Path</div>')
    if not log:
        html.append('<p style="color:#888">No rules were triggered.</p>')
    for step in log:
        conds = " <b>AND</b> ".join(f'<span style="color:#f0c060">{c.replace("_"," ")}</span>' for c in step.triggered_by)
        conc  = step.conclusion_added.replace("_"," ").title()
        html.append(
            f'<div class="step-box">'
            f'<span class="step-num">Step {step.step_number}</span> &nbsp;'
            f'<span class="step-rule">[{step.rule.rule_id}] {step.rule.name}</span><br>'
            f'<span style="color:#888;font-size:.82rem">IF&nbsp;</span>{conds}<br>'
            f'<span style="color:#888;font-size:.82rem">THEN&nbsp;</span>'
            f'<span class="step-conc">{conc}</span><br>'
            + (f'<div class="step-why">💡 {step.rule.explanation}</div>' if step.rule.explanation else '')
            + '</div>'
        )
    html.append('</div>')

    # ── Conclusions ───────────────────────────────────────────
    html.append('<div class="es-section">')
    html.append('<div class="es-title" style="color:#e2e8f0">🩺 Conclusions</div>')
    if not inferred:
        html.append('<p style="color:#888">No conclusions could be drawn from the given symptoms.</p>')
    if emergency:
        html.append('<div style="margin-bottom:8px"><span style="color:#ff6b6b;font-weight:700">🚨 EMERGENCY — Seek immediate help!</span></div>')
        for k in emergency:
            html.append(f'<span class="badge-em">⚡ {k.replace("_"," ").title()}</span>')
    if diagnoses:
        html.append('<div style="margin:10px 0 4px;color:#7ec87e;font-weight:600">Probable Diagnoses</div>')
        for k in diagnoses:
            html.append(f'<span class="badge-diag">● {k.replace("_"," ").title()}</span>')
    if warnings:
        html.append('<div style="margin:10px 0 4px;color:#f0c060;font-weight:600">⚠️ Recommendations / Risks</div>')
        for k in warnings:
            html.append(f'<span class="badge-warn">▸ {k.replace("_"," ").title()}</span>')
    html.append('</div>')

    # ── Stats ─────────────────────────────────────────────────
    html.append('<div class="es-section">')
    html.append('<div class="es-title" style="color:#888">📊 Run Statistics</div>')
    html.append('<div class="stat-row">')
    for val, lbl in [
        (len(MEDICAL_RULES), "Rules in KB"),
        (len(engine.fired_rules), "Rules Fired"),
        (len(log), "Inference Steps"),
        (len(inferred), "Conclusions"),
    ]:
        html.append(f'<div class="stat-pill"><div class="stat-val">{val}</div><div class="stat-lbl">{lbl}</div></div>')
    html.append('</div></div>')

    html.append('</div>')  # .es-box
    display(HTML("".join(html)))

print("✓ Display helpers loaded")

"""---
## 📖 5. View Knowledge Base Rules

Run the cell below to display all 17 rules in a formatted table.

"""

def show_rules():
    rows = []
    rows.append("<style>"
        ".kb-table{border-collapse:collapse;width:100%;font-family:'Segoe UI',sans-serif;font-size:.85rem}"
        ".kb-table th{background:#252535;color:#7ab8e8;padding:8px 12px;text-align:left;border-bottom:2px solid #7ab8e855}"
        ".kb-table td{padding:7px 12px;border-bottom:1px solid #2a2a3a;vertical-align:top}"
        ".kb-table tr:hover td{background:#1a1a2e}"
        ".cond-chip{background:#3a3010;color:#f0c060;border-radius:4px;padding:1px 6px;margin:2px;display:inline-block;font-size:.78rem}"
        ".conc-chip{background:#0f2a1a;color:#7ec87e;border-radius:4px;padding:1px 6px;font-size:.78rem}"
        ".pri-high{color:#ff6b6b;font-weight:700}"
        ".pri-med{color:#f0c060}"
        ".pri-low{color:#7ab8e8}"
        "</style>")
    rows.append('<table class="kb-table"><thead><tr>'
        '<th>ID</th><th>Rule Name</th><th>Conditions (IF)</th><th>Conclusion (THEN)</th><th>Priority</th>'
        '</tr></thead><tbody>')
    for r in MEDICAL_RULES:
        conds = " ".join(f'<span class="cond-chip">{c.replace("_"," ")}</span>' for c in r.conditions)
        conc  = f'<span class="conc-chip">{r.conclusion.replace("_"," ").title()}</span>'
        pri_cls = "pri-high" if r.priority >= 8 else ("pri-med" if r.priority >= 5 else "pri-low")
        rows.append(f'<tr><td><b>{r.rule_id}</b></td><td>{r.name}</td><td>{conds}</td><td>{conc}</td>'
                    f'<td class="{pri_cls}">{r.priority}</td></tr>')
    rows.append('</tbody></table>')
    display(HTML("".join(rows)))

show_rules()

"""---
## 🎛️ 6. Interactive Symptom Checker

Select symptoms using the checkboxes below, then click **Run Inference**.  
Use the **Load Demo** dropdown to auto-populate a scenario.

"""

import ipywidgets as widgets
from IPython.display import clear_output

# ── Build symptom checkboxes ──────────────────────────────────
symptom_keys  = list(ALL_SYMPTOMS.keys())
symptom_labels = list(ALL_SYMPTOMS.values())

checkboxes = [
    widgets.Checkbox(value=False, description=symptom_labels[i],
                     layout=widgets.Layout(width="340px"),
                     style={"description_width": "0px"})
    for i in range(len(symptom_keys))
]

# Grid: 3 columns
cols = 3
rows_w = []
for i in range(0, len(checkboxes), cols):
    rows_w.append(widgets.HBox(checkboxes[i:i+cols]))
symptoms_box = widgets.VBox(rows_w)

# ── Demo dropdown ─────────────────────────────────────────────
demo_dd = widgets.Dropdown(
    options=["(Select a demo scenario)"] + list(DEMO_SCENARIOS.keys()),
    description="Load Demo:",
    layout=widgets.Layout(width="380px"),
    style={"description_width": "100px"},
)

def on_demo_change(change):
    if change["new"] == "(Select a demo scenario)":
        return
    scenario_symptoms = DEMO_SCENARIOS[change["new"]]
    for cb, key in zip(checkboxes, symptom_keys):
        cb.value = key in scenario_symptoms

demo_dd.observe(on_demo_change, names="value")

# ── Buttons ───────────────────────────────────────────────────
run_btn   = widgets.Button(description="▶  Run Inference",
                           button_style="success",
                           layout=widgets.Layout(width="160px", height="36px"))
clear_btn = widgets.Button(description="✕  Clear All",
                           button_style="warning",
                           layout=widgets.Layout(width="120px", height="36px"))
output    = widgets.Output()

def on_run(b):
    selected = {key: True for key, cb in zip(symptom_keys, checkboxes) if cb.value}
    with output:
        clear_output(wait=True)
        if not selected:
            display(HTML('<p style="color:#f0c060;font-family:sans-serif">⚠️ Please select at least one symptom.</p>'))
            return
        engine = ForwardChainer(MEDICAL_RULES)
        engine.load_facts(selected)
        engine.run()
        render_results(engine, set(selected.keys()))

def on_clear(b):
    for cb in checkboxes:
        cb.value = False
    demo_dd.value = "(Select a demo scenario)"
    with output:
        clear_output()

run_btn.on_click(on_run)
clear_btn.on_click(on_clear)

# ── Layout ────────────────────────────────────────────────────
header = widgets.HTML('<h3 style="font-family:sans-serif;color:#7ab8e8;margin-bottom:8px">Select Symptoms</h3>')
demo_row = widgets.HBox([demo_dd])
btn_row  = widgets.HBox([run_btn, clear_btn], layout=widgets.Layout(gap="10px", margin="12px 0"))

display(widgets.VBox([header, demo_row, symptoms_box, btn_row, output]))

"""---
## 🐍 7. Programmatic API

You can also call the engine directly in code — no widgets needed.

"""

# ── Example: Cardiac Emergency ───────────────────────────────
symptoms = {
    "chest_pain":        True,
    "shortness_of_breath": True,
    "dizziness":         True,
    "left_arm_pain":     True,
}

engine = ForwardChainer(MEDICAL_RULES)
engine.load_facts(symptoms)
engine.run()

render_results(engine, set(symptoms.keys()))

"""---
## 📄 8. Plain-Text Inference Log

Inspect the reasoning trace as plain Python objects — useful for debugging or extending the system.

"""

# Reuse last engine run from Cell 7
print(f"{'─'*60}")
print(f"  Inference Log  ({len(engine.inference_log)} steps)")
print(f"{'─'*60}")
for step in engine.inference_log:
    conds = " AND ".join(step.triggered_by)
    conc  = step.conclusion_added.replace("_", " ").title()
    print(f"  Step {step.step_number}: [{step.rule.rule_id}] {step.rule.name}")
    print(f"    IF   : {conds}")
    print(f"    THEN : {conc}")
    if step.rule.explanation:
        print(f"    Why  : {step.rule.explanation}")
    print()

print(f"  Fired rules  : {sorted(engine.fired_rules)}")
print(f"  Final facts  : {list(engine.facts.keys())}")

"""---
## 🧪 9. Unit Tests

Run the cell below to verify the engine is correct.  
All 9 tests should pass.

"""

def run_tests():
    passed = failed = 0

    def check(name, condition, msg=""):
        nonlocal passed, failed
        if condition:
            print(f"  ✅  {name}")
            passed += 1
        else:
            print(f"  ❌  {name}  →  {msg}")
            failed += 1

    def make(rules, facts):
        e = ForwardChainer(rules)
        e.load_facts(facts)
        e.run()
        return e

    # 1. Single rule fires
    e = make([Rule("R1","T",["a","b"],"c")], {"a":True,"b":True})
    check("Single rule fires", e.facts.get("c") is True)

    # 2. Missing condition blocks rule
    e = make([Rule("R1","T",["a","b"],"c")], {"a":True})
    check("Incomplete conditions block rule", "c" not in e.facts)

    # 3. Multi-step chaining
    rules = [Rule("R1","S1",["a"],"b",priority=2), Rule("R2","S2",["b","c"],"d",priority=1)]
    e = make(rules, {"a":True,"c":True})
    check("Multi-step chain: step 1", e.facts.get("b") is True)
    check("Multi-step chain: step 2", e.facts.get("d") is True)
    check("Multi-step chain: 2 steps logged", len(e.inference_log) == 2)

    # 4. Priority ordering
    rules = [Rule("RL","Low",["x"],"lo",priority=1), Rule("RH","High",["x"],"hi",priority=9)]
    e = make(rules, {"x":True})
    check("Priority: high fires first", e.inference_log[0].rule.rule_id == "RH")

    # 5. No double firing
    e = make([Rule("R1","T",["a"],"b")], {"a":True})
    check("No double firing", len(e.inference_log) == 1)

    # 6. Flu integration
    e = make(MEDICAL_RULES, {"fever":True,"high_fever":True,"body_aches":True,"fatigue":True,"cough":True})
    check("Flu: influenza diagnosed",   e.facts.get("influenza") is True)
    check("Flu: severe risk flagged",   e.facts.get("severe_flu_risk") is True)

    # 7. Cardiac emergency integration
    e = make(MEDICAL_RULES, {"chest_pain":True,"shortness_of_breath":True,"dizziness":True,"left_arm_pain":True})
    check("Cardiac: concern detected",  e.facts.get("cardiac_concern") is True)
    check("Cardiac: emergency flagged", e.facts.get("emergency_heart_attack") is True)

    print(f"\n  {'─'*36}")
    print(f"  Results: {passed} passed, {failed} failed")
    return failed == 0

all_ok = run_tests()

"""---
## ➕ 10. Add Your Own Rules

Adding new rules is just appending a `Rule` object — no engine changes needed.

"""

# Example: Add a COVID-19 screening rule
covid_rules = [
    Rule("R18", "COVID-19 Screening",
         conditions=["fever", "cough", "fatigue", "difficulty_breathing"],
         conclusion="covid19_screening_advised",
         explanation="Combination of fever, cough, fatigue, breathing difficulty → COVID-19 test advised.",
         priority=6),
    Rule("R19", "COVID-19 Isolation Protocol",
         conditions=["covid19_screening_advised", "runny_nose"],
         conclusion="isolation_protocol_required",
         explanation="Positive COVID-19 screening with additional symptoms → isolation.",
         priority=8),
]

extended_rules = MEDICAL_RULES + covid_rules
print(f"Extended KB: {len(extended_rules)} rules")

# Test it
engine2 = ForwardChainer(extended_rules)
engine2.load_facts({"fever":True, "cough":True, "fatigue":True,
                    "difficulty_breathing":True, "runny_nose":True})
engine2.run()
render_results(engine2, {"fever","cough","fatigue","difficulty_breathing","runny_nose"})

"""---
*Rule-Based Expert System · Forward Chaining · Python 3.10+ · ipywidgets*  
*Built for educational purposes — not for real medical diagnosis.*

"""